import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto px-6 py-12">
      <Link href="/" className="text-sm text-violet-700 hover:underline mb-6 inline-block">
        ← Back to StyleMe
      </Link>

      <h1 className="text-3xl font-bold text-slate-900 mb-2">Terms of Service</h1>
      <p className="text-sm text-slate-500 mb-8">Last updated: March 2026</p>

      <div className="prose prose-slate max-w-none text-[15px] leading-relaxed space-y-6">
        <section>
          <h2 className="text-xl font-semibold text-slate-800 mb-2">Acceptance of terms</h2>
          <p className="text-slate-600">
            By creating an account or using StyleMe, you agree to these Terms of Service. If you do not
            agree, do not use the app.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 mb-2">Eligibility</h2>
          <p className="text-slate-600">
            You must be at least 13 years old to use StyleMe. By creating an account, you confirm that
            you meet this age requirement. We reserve the right to terminate accounts that violate this
            requirement.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 mb-2">Your account</h2>
          <p className="text-slate-600">
            You are responsible for maintaining the security of your account credentials. StyleMe uses
            Clerk for authentication — your password is never stored by StyleMe directly. You are
            responsible for all activity that occurs under your account.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibent text-slate-800 mb-2">Your content</h2>
          <p className="text-slate-600">
            Photos and content you upload to StyleMe remain yours. By uploading content, you grant
            StyleMe a limited licence to process and store that content solely to provide the service
            to you. We do not use your content for any other purpose, including AI model training.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 mb-2">Acceptable use</h2>
          <p className="text-slate-600">
            You agree not to: upload illegal or harmful content; attempt to reverse-engineer the app;
            use the service for any commercial purpose without permission; or misuse the service in
            any way that could damage StyleMe or its users.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 mb-2">AI-generated content</h2>
          <p className="text-slate-600">
            Outfit suggestions and style recommendations are generated by AI and are for informational
            and entertainment purposes only. StyleMe does not guarantee the accuracy or suitability of
            any AI-generated content for your specific needs.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 mb-2">Service availability</h2>
          <p className="text-slate-600">
            StyleMe is provided &ldquo;as is&rdquo; without warranties of any kind. We may modify,
            suspend, or discontinue the service at any time without notice. We are not liable for any
            interruption to the service.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 mb-2">Account deletion</h2>
          <p className="text-slate-600">
            You may delete your account at any time from the Privacy &amp; Data screen. Deletion is
            permanent and immediate — all your data will be removed and cannot be recovered.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 mb-2">Changes to terms</h2>
          <p className="text-slate-600">
            We may update these terms from time to time. Continued use of StyleMe after changes
            constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-slate-800 mb-2">Contact</h2>
          <p className="text-slate-600">
            For any questions about these terms, please contact us via the StyleMe app.
          </p>
        </section>
      </div>
    </div>
  );
}
